#!/bin/bash

# Base script generated by NERSC Batch Script Generator on https://iris.nersc.gov/jobscript.html

#SBATCH -N 1
#SBATCH -C cpu
#SBATCH -q regular
#SBATCH -J weights
#SBATCH --mail-user=ekoehn@lbl.gov
#SBATCH --mail-type=ALL
#SBATCH -A m3513
#SBATCH -t 05:00:0

# OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread
module load python
conda activate fly
echo $CONDA_PREFIX
echo "$PWD"
cd /pscratch/sd/e/ekoehn/FlyStability

#Usage: train_rd_model [OPTIONS]
# Options:
#   --n INTEGER                     Size of the model, number of neurons used
#                                   [required]
#   --n_samples INTEGER             Number of sample used, (default:1)
#                                   [required]
#   --nle INTEGER                   Number of Lyapunov exponent used  [required]
#   --g FLOAT                       Synaptic distribution parameter  [required]
#   --n_epochs INTEGER              Number of epochs used
#   --activation [tanh|tanh_pos|tanh_streched]
#                                   Which loss we want to use for the
#                                   optimisation  [required]
#   --loss [l2|MSE]                 Which loss we want to use for the
#                                   optimisation  [required]
#   --target FLOAT                  Target lyapunov vector
#   --tons FLOAT                    Step size between two consecutive QR facto
#   --tsim INTEGER                  Length of the simulation [tau]
#   --train_weights BOOLEAN         Optimizition on the weights
#   --train_shifts BOOLEAN          Optimizition on the shitfs
#   --train_gains BOOLEAN           Optimizition on the gains
#   --lr FLOAT                      Learning rate used
#   --early_stopping FLOAT          Value of the loss at wich the optimization
#                                   would stop
#   --help                          Show this message and exit.
# Define parameters



n=100
n_samples=1

g=1  # Define the value for the synaptic distribution parameter
n_epochs=1000

activation="tanh_pos"
loss="Sinai"
target=100.

tons=0.2
tsim=200

train_weights="True"
train_gains="False"
train_shifts="False"

lr=0.1
early_crit=1e-3

# Loop over different nle values
for nle in 100
do
    command="train_rd_model --n $n --n_samples $n_samples --nle $nle --g $g --n_epochs $n_epochs  --activation $activation --loss $loss --target $target --tons $tons --tsim $tsim   --train_weights $train_weights --train_shifts $train_shifts --train_gains $train_gains  --lr $lr --early_stopping $early_crit"
    echo $command
    srun -n 1  --cpu_bind=cores $command
done
